const NOTIFICATION_GROUP = {
  UNREAD: 0,
  AGENTS: 1,
  BILLS: 2,
  CORP: 3,
  MISC: 4,
  OLD: 5,
  SOV: 6,
  STRUCTURES: 7,
  WAR: 8,
  CONTACTS: 9,
  BOUNTIES: 10,
  INSURANCE: 11,
  SKILL_TRAINING: 12,
  CCP: 14,
  RAFFLE: 15,
  INSURGENCIES: 16,
};

const NOTIFICATION_TYPE = {
  NEW_MAIL_FROM: 1004,
  MAIL_SUMMARY: 1003,
  SKILL_FINISHED: 1000,
  SKILL_EMPTY_QUEUE: 1002,
  CONTACT_SIGNED_ON: 2001,
  CONTACT_SIGNED_OFF: 2002,
  EXPERT_SYSTEM_EXPIRY_IMMINENT: 252,
  EXPERT_SYSTEM_EXPIRED: 253,
  STRUCTURE_ITEMS_TO_ASSET_SAFETY: 190,
  STRUCTURE_ITEMS_DELIVERED: 199,
};

module.exports = {
  NOTIFICATION_GROUP,
  NOTIFICATION_TYPE,
};
